---
- name: configure acls
  hosts: asa
  connection: network_cli
  gather_facts: yes
  become: yes
  become_method: enable
  tasks:
    - cisco.asa.asa_acl:
        lines:
        - access-list ACL-OUTSIDE extended permit tcp any any eq www
        - access-list ACL-OUTSIDE extended permit tcp any any eq https

