---
- name: configure acls
  hosts: asa
  connection: network_cli
  gather_facts: yes
  become: yes
  become_method: enable
  tasks:
    - name: Gather all legacy facts
      cisco.asa.asa_facts:
        gather_subset: all

    - name: Gather only the config and default facts
      cisco.asa.asa_facts:
        gather_subset:
        - config

    - name: Do not gather hardware facts
      cisco.asa.asa_facts:
        gather_subset:
        - '!hardware'

    - name: Gather legacy and resource facts
      cisco.asa.asa_facts:
        gather_subset: all
