---
- name: configure acls
  hosts: asa
  connection: network_cli
  gather_facts: yes
  become: yes
  become_method: enable
  tasks:
    - name: Create an Object 
      cisco.asa.asa_config:
        lines:
        - object-group network test
        - network-object host 10.80.30.18
        - network-object host 10.80.30.19
        - network-object host 10.80.30.20

